"namespace" = { fg = "gray", modifiers = ["dim"] }

"type" = { fg = "gray" }
"type.builtin" = { fg = "gold" }
"type.enum" = { fg = "blue"}

"constructor" = { fg = "gray", modifisers = ["bold"] }

"constant" = { fg = "red" }
# "constant.builtin" = {}
# "constant.builtin.boolean" = {}
# "constant.character" = {}
# "constant.numeric" = {}

"string" = "yellow"
# "string.regexp" = {}
# "string.special" = {}
"string.special.path" = { fg = "orange" }
# "string.special.url" = {}
"string.special.symbol" = { fg = "gray" }

"comment" = { fg = "gray", modifiers = ["dim"] }
"comment.block" = { fg = "gray", modifiers = ["dim"] }
"comment.block.documentation" = { fg = "gray", modifiers = ["dim"] }

"variable" = { fg = "blue" }
# "variable.builtin" = { fg = "dark-blue" }
# "variable.other" = { fg = "light-blue" }
# "variable.parameter" = {}

"punctuation" = { fg = "gray", modifiers = ["dim"] }
"punctuation.delimiter" = { fg = "gray" }
"punctuation.bracket" = { fg = "gray" }
"punctuation.special" = "orange"

"keyword" = { fg = "purple" }
"keyword.control" = { fg = "pink" }
"keyword.operator" = { fg = "pink" }
"keyword.directive" = { fg = "pink" }
"keyword.function" = { fg = "gold" }
"keyword.storage" = { fg = "pink" }
# "keyword.storage.type" = { fg = "purple" }
"keyword.storage.modifier" = { fg = "purple" }

"operator" = { fg = "gray" }
"function" = { fg = "light-gray", modifiers = [] }
# "function.method" = {}
# "function.builtin" = {}
# "function.macro" = {}
# "function.special" = {}

"label" = "cyan"
"special" = "orange" # This hits on derive,? in rust
"tag" = "blue"
"attribute" = "gold"

"markup.heading" = { fg = "gold", modifiers = ["bold"]}
"markup.marker" = { fg = "gold", modifiers = ["dim"]}
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.list" = "gold"
"markup.link.url" = { fg = "dark-blue", modifiers = ["underlined"] }
"markup.link.label" = { fg = "dark-blue"}
"markup.link.text" = { fg = "dark-blue" }
"markup.quote" = "teal"
"markup.raw" = "light-green"

"diff.plus" = "ui-info"
"diff.minus" = "ui-error"
"diff.delta" = "ui-warning"

# "markup.normal.completion" = { bg = "cyan", fg = "gray" }
# "markup.normal.hover" = {}
# "markup.heading.completion" = {}
# "markup.heading.hover" = {}
# "markup.raw.inline.completion" = {}
# "markup.raw.inline.hover" = {}

"ui.background" = { bg = "black", fg = "ui" }

"ui.cursor" = { fg = "black", bg = "white" }
"ui.cursor.match" = { bg = "white", fg = "black" }
# "ui.cursor.normal" = {}
# "ui.cursor.insert" = {}
# "ui.cursor.select" = { }
# "ui.cursor.primary" = {}
# "ui.cursor.primary.normal" = {}
# "ui.cursor.primary.insert" = {}
# "ui.cursor.primary.select" = {}

"ui.debug.breakpoint" = "pink"
"ui.debug.active" = "purple"
"ui.highlight.frameline" = { fg = "purple" }
"ui.gutter" = {}
"ui.gutter.selected" = {}
"ui.linenr" = { fg = "ui-detail", modifiers = [] }
"ui.linenr.selected" = { fg = "gray", modifiers = ["bold"] }

"ui.statusline" = { fg = "gray", bg = "ui-detail" }
"ui.statusline.inactive" = { fg = "gray", modifiers = ["dim"], bg = "ui-detail" }
"ui.statusline.normal" = { bg = "green", modifiers = ["bold"] }
"ui.statusline.insert" = { bg = "ui-error", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "ui-warning", fg = "black", modifiers = ["bold"] }

# Documentation popups, e.g. SPC+k
"ui.popup" = { bg = "ui-detail2", fg = "gray" }

# Line between splits
"ui.window" = { fg = "ui-detail" }

"ui.text" = "gray"

# Text suggestions
"ui.text.inactive" = { modifiers = ["dim"] }

# The focused text in pickers
"ui.text.focus" = { bg = "ui-alt", fg = "magenta" }

# Popup window, e.g. triggered by SPC
"ui.popup.info" = { bg = "black", fg = "ui-detail" }
"ui.text.info" = "gray"

# Help box above the bottom menu 
"ui.help" = { bg = "black", fg = "ui" }

# Completion menu
"ui.menu" = { fg = "gray", bg = "ui-detail2" }
"ui.menu.selected" = { fg = "gold", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "gray", bg = "ui-detail2" }

"ui.virtual.ruler" = { bg = "ui-alt" }
"ui.virtual.indent-guide" = "ui-alt"
"ui.virtual.whitespace" = { fg = "gray", modifiers = ["dim"]}
"ui.virtual.wrap" = { fg = "gray", modifiers = ["dim"]}
"ui.virtual.inlay-hint" = { bg = "ui-detail", fg = "gray", modifiers = ["dim"]}
# "ui.virtual.inlay-hint.parameter" = {}
# "ui.virtual.inlay-hin.type" = {}

"ui.selection" = { fg = "white", bg = "ui-detail" }
"ui.highlight" = { fg = "pink"}
"ui.cursorline" = { bg = "ui-alt" }

warning = "ui-warning"
error = "ui-error"
info = "ui-info"
hint = "ui-hint"

"diagnostic.hint" = { underline = { color = "ui-hint", style = "dotted"} }
"diagnostic.info" = { underline = { color = "ui-info", style = "dotted"} }
"diagnostic.warning" = { underline = { color = "ui-warning", style = "curl"} }
"diagnostic.error" = { underline = { color = "ui-error", style = "curl"} }

[palette]
ui         = "#384657" 
ui-alt     = "#181e25" 
ui-detail  = "#303c4b" 
ui-detail2 = "#28323e"
ui-error   = "#ad343e"
ui-warning = "#f3de8a"
ui-info    = "#136f63"
ui-hint    = "#477998"

dark-blue = "#1d3557"

black  = "#101419"
red    = "#db878e"
yellow = "#f6f5ae"
blue   = "#83b7c9"
gray   = "#eceaea"
pink   = "#e87aa8"
orange = "#e7947b"
purple = "#9989d9"
white  = "#f5f4f4"
gold   = "#dbc987"
