theme = "base16_terminal"

[editor]
true-color = true
mouse = true
line-number = "absolute"
cursorline = true
auto-save = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name"]
right = ["selections", "position", "file-encoding", "file-type"]

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
"#" = "toggle_comments"
"C-c" = "no_op"