theme = "arbitrary"

[editor]
true-color = true
mouse = true
line-number = "absolute"
cursorline = true
auto-save = true
rulers = [80]
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "position-percentage", "file-encoding", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
"#" = "toggle_comments"
"C-c" = "no_op"
"C-down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"C-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]